// PACK ITEM TYPES
export const GET_PACK_ITEMS = 'GET_PACK_ITEMS';
export const CREATE_PACK_ITEM = 'CREATE_PACK_ITEM';
export const DELETE_PACK_ITEM = 'DELETE_PACK_ITEM';
export const LOADING_PACK_ITEMS = 'LOADING_PACK_ITEMS';

// PHOTO ITEM TYPES
export const GET_PHOTO_ITEMS = 'GET_PHOTO_ITEMS';
export const LOADING_PHOTO_ITEMS = 'LOADING_PACK_ITEMS';
